#user é…ç½®ï¼Œè¿æ¥ lab-28-quartz-jdbc-user åº“ã€‚ç›®çš„æ˜¯ï¼Œä¸ºäº†æ¨¡æ‹Ÿæˆ‘ä»¬ä¸€èˆ¬é¡¹ç›®ï¼Œä½¿ç”¨åˆ°çš„ä¸šåŠ¡æ•°æ®åº“ã€‚
#quartz é…ç½®ï¼Œè¿æ¥ lab-28-quartz-jdbc-quartz åº“ã€‚ç›®çš„æ˜¯ï¼ŒQuartz ä¼šä½¿ç”¨å•ç‹¬çš„æ•°æ®åº“ã€‚ğŸ˜ˆ å¦‚æœæˆ‘ä»¬æœ‰å¤šä¸ªé¡¹ç›®éœ€è¦ä½¿ç”¨åˆ° Quartz æ•°æ®åº“çš„è¯ï¼Œå¯ä»¥ç»Ÿä¸€ä½¿ç”¨ä¸€ä¸ªï¼Œä½†æ˜¯è¦æ³¨æ„é…ç½® spring.quartz.scheduler-name è®¾ç½®ä¸åŒçš„ Scheduler åå­—ï¼Œå½¢æˆä¸åŒçš„ Quartz é›†ç¾¤ã€‚
spring:
  datasource:
    user:
      url: jdbc:mysql://192.168.252.110:3306/lab-28-quartz-jdbc-user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
    quartz:
      url: jdbc:mysql://192.168.252.110:3306/lab-28-quartz-jdbc-quartz?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root

  # Quartz çš„é…ç½®ï¼Œå¯¹åº” QuartzProperties é…ç½®ç±»
  quartz:
    scheduler-name: clusteredScheduler # Scheduler åå­—ã€‚é»˜è®¤ä¸º schedulerName
    job-store-type: jdbc # Job å­˜å‚¨å™¨ç±»å‹ã€‚é»˜è®¤ä¸º memory è¡¨ç¤ºå†…å­˜ï¼Œå¯é€‰ jdbc ä½¿ç”¨æ•°æ®åº“ã€‚
    auto-startup: true # Quartz æ˜¯å¦è‡ªåŠ¨å¯åŠ¨
    startup-delay: 0 # å»¶è¿Ÿ N ç§’å¯åŠ¨
    wait-for-jobs-to-complete-on-shutdown: true # åº”ç”¨å…³é—­æ—¶ï¼Œæ˜¯å¦ç­‰å¾…å®šæ—¶ä»»åŠ¡æ‰§è¡Œå®Œæˆã€‚é»˜è®¤ä¸º false ï¼Œå»ºè®®è®¾ç½®ä¸º true
    overwrite-existing-jobs: false # æ˜¯å¦è¦†ç›–å·²æœ‰ Job çš„é…ç½®
    properties: # æ·»åŠ  Quartz Scheduler é™„åŠ å±æ€§ï¼Œæ›´å¤šå¯ä»¥çœ‹ http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html æ–‡æ¡£
      org:
        quartz:
          # JobStore ç›¸å…³é…ç½®
          jobStore:
            # æ•°æ®æºåç§°
            dataSource: quartzDataSource # ä½¿ç”¨çš„æ•°æ®æº
            class: org.quartz.impl.jdbcjobstore.JobStoreTX # JobStore å®ç°ç±»
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_ # Quartz è¡¨å‰ç¼€
            isClustered: true # æ˜¯é›†ç¾¤æ¨¡å¼
            clusterCheckinInterval: 1000
            useProperties: false
          # çº¿ç¨‹æ± ç›¸å…³é…ç½®
          threadPool:
            threadCount: 25 # çº¿ç¨‹æ± å¤§å°ã€‚é»˜è®¤ä¸º 10 ã€‚
            threadPriority: 5 # çº¿ç¨‹ä¼˜å…ˆçº§
            class: org.quartz.simpl.SimpleThreadPool # çº¿ç¨‹æ± ç±»å‹
    jdbc: # ä½¿ç”¨ JDBC çš„ JobStore çš„æ—¶å€™ï¼ŒJDBC çš„é…ç½®
      initialize-schema: never # æ˜¯å¦è‡ªåŠ¨ä½¿ç”¨ SQL åˆå§‹åŒ– Quartz è¡¨ç»“æ„ã€‚è¿™é‡Œè®¾ç½®æˆ never ï¼Œæˆ‘ä»¬æ‰‹åŠ¨åˆ›å»ºè¡¨ç»“æ„ã€‚